### PR TITLE
Add Pycraft section to site

### PR DESCRIPTION
**Pull request by olls**

### CODE REVIEW

**Comment by grit96** [comment]
Why assign to me?

**Comment by olls** [comment]
I've already accepted it, you need to now...

Anyway, just noticed a problem, don't merge yet!

**Comment by olls** [comment]
Now it's good

**Comment by grit96** [comment]
I wonder if there's a way we can improve GHL to build PRs in an isolated environment?

**Comment by olls** [comment]
Hmm, that would be good.

**Pull request merged**
